
objc_library(
    name = "OverlayStatusControllerImpl",
    module_name = "OverlayStatusControllerImpl",
    srcs = glob([
        "Sources/**/*.m",
    ]),
    hdrs = glob([
        "Sources/**/*.h",
    ]),
    includes = [
        "Sources",
    ],
    copts = [
        "-Werror",
        "-Wno-deprecated-declarations",
    ],
    visibility = [
        "//visibility:public",
    ],
)
